name: ai-scm-portfolio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pulp
  - simpy
  - pip:
      - shap
      - prophet
      - tensorflow
      - opencv-python
      - tiktoken
      - langchain
      - openai
# Notes:
# - 'tensorflow' and 'opencv-python' are optional/heavy; remove if not needed.
# - On Windows, Prophet may require a C++ build toolchain; alternatively use 'neuralprophet' or stick to RF/XGBoost.
# - Create with:    conda env create -f environment.yml
# - Update with:    conda env update -f environment.yml --prune
# - Activate:       conda activate ai-scm-portfolio
