name: ai-scm-portfolio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pulp
  - pip:
      - web3
      - eth-account
      - python-dotenv
      - pydantic
      - fastapi
# Notes:
# - Keep pip deps minimal at first; you can add more as needed.
# - Create:  conda env create -f environment.yml
# - Update:  conda env update -f environment.yml --prune
# - Activate: conda activate ai-scm-portfolio