name: analytics_portfolio
channels:
  - conda-forge
  - defaults
dependencies:
  # --- Python runtime ---
  - python=3.11
  - pip

  # --- Jupyter & friends ---
  - jupyterlab
  - ipykernel
  - nb_conda_kernels
  - ipywidgets

  # --- Core analytics stack ---
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels

  # --- Viz & storytelling ---
  - matplotlib
  - plotly
  - seaborn

  # --- Data IO / ETL ---
  - pyarrow           # Parquet/Arrow; great for columnar data
  - openpyxl          # Excel .xlsx read/write
  - xlrd              # Legacy Excel reader
  - sqlalchemy
  - requests
  - beautifulsoup4
  - lxml
  - pyyaml

  # --- Graphs / causal / optimization / sim ---
  - networkx
  - graphviz
  - python-graphviz   # for rendering DOT graphs
  - shap
  - lime
  - pulp              # Linear programming alternative
  - simpy             # Discrete-event simulation
  - mesa              # Agent-based simulation (ABM)

  # --- Dev experience & QA ---
  - black
  - isort
  - pre-commit
  - pytest

  # --- Optional: Bayesian/causal (uncomment as needed) ---
  # - pymc             # Bayesian modeling (heavier)
  # - arviz            # Diagnostics for Bayesian models

  # Some causal/DAG libs are pip-first. Keep them here so env stays reproducible.
  - pip:
    - ortools
      # Causal graphs & inference
      # (Uncomment if/when needed. If install errors occur, try in WSL.)
      # - dowhy
      # - econml
      # - causalnex
      # - pgmpy

      # Knowledge graphs (optional; pip ecosystem is more up-to-date)
      # - rdflib
      # - owlready2
