[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]   # basics: pyflakes/pycodestyle/imports/bugbear/pyupgrade
ignore = []                           # add ignores here if needed
fix = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
